class Packet:
    source: int
    dest: int
    app_number: int
    data: bytes
    def __init__(self, dest: int, app_number: int, data: bytes) -> None: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, int | bytes]: ...
