from typing import Literal

import framebuf
from microfont import MicroFont

type Color = Literal[0, 1]

width: Literal[200]
height: Literal[200]

def show() -> None: ...
def fill(color: Color) -> None: ...
def pixel(x: int, y: int, color: Color) -> None: ...
def hline(x: int, y: int, w: int, color: Color) -> None: ...
def vline(x: int, y: int, h: int, color: Color) -> None: ...
def line(x1: int, y1: int, x2: int, y2: int, color: Color) -> None: ...
def rect(x: int, y: int, w: int, h: int, color: Color) -> None: ...
def fill_rect(x: int, y: int, w: int, h: int, color: Color) -> None: ...
def text(text: str, x: int, y: int, color: Color = 0) -> None: ...
def nice_text(
    text: str,
    x: int,
    y: int,
    font: int | MicroFont = 18,
    color: int = 0,
    *,
    rot: int = 0,
    x_spacing: int = 0,
    y_spacing: int = 0,
) -> None: ...
def blit(fb: framebuf.FrameBuffer, x: int, y: int) -> None: ...
def import_pbm(file_path: str) -> framebuf.FrameBuffer: ...
